### ISSUE TITLE
Fix the UI

### ISSUE THREAD

**Issue by sxijyoti** [acmpesuecc/SaveMe#1]
Change the GUI and fix the alignment issues. Make it look neat. Change the font as well
You are free to change the theme and the images too but make sure it's true to the nature of the plotline. 

NOTE: 250 points is assigned to this issue but it will only be awarded if the GUI is exceptionally good.

Happy hacking! :)

**Comment by Nishanth2465** [comment]
can i get assined?

**Comment by Aditya-C-S** [comment]
can u assign this to me please

**Comment by sxijyoti** [comment]
!assign @Aditya-C-S

**Comment by Hemaksh-b** [comment]
can i be assigned this?

**Comment by Aditya-C-S** [comment]
i am going to have dinner , let me come back and finish it

**Comment by sxijyoti** [comment]
!extend 45

**Comment by Aditya-C-S** [comment]
@sjp-codes  i just need 10 more min , i will finish it

**Comment by Aditya-C-S** [comment]
fixed #1

**Comment by Git-Cat-21** [comment]
can i be assigned to it

**Comment by sxijyoti** [comment]
@Aditya-C-S send pull request

**Comment by sxijyoti** [comment]
!deassign @Aditya-C-S

**Comment by sxijyoti** [comment]
!assign @Hemaksh-b

**Comment by Aditya-C-S** [comment]
> @Aditya-C-S send pull request

i already sent pull request

**Comment by ShashankPatali** [comment]
Can you assign this to me

**Comment by Darshanpawar7** [comment]
assign me this @sjp-codes

**Comment by ShashankPatali** [comment]
@sjp-codes any updates on assigning

**Comment by sxijyoti** [comment]
!deassign @Hemaksh-b

**Comment by sxijyoti** [comment]
!assign @Git-Cat-21

**Comment by Git-Cat-21** [comment]
deassign

**Comment by sxijyoti** [comment]
!deassign @Git-Cat-21

**Comment by sxijyoti** [comment]
!assign @ShashankPatali

**Comment by ShashankPatali** [comment]
If the time is almost over, please if possible extend it by half an hour. I had some issues with tkinter not working

**Comment by sxijyoti** [comment]
!extend 35

**Comment by sxijyoti** [comment]
!deassign @ShashankPatali

**Comment by sxijyoti** [comment]
!assign @ShashankPatali

**Comment by ShashankPatali** [comment]
deassign

**Comment by sxijyoti** [comment]
!deassign @ShashankPatali

**Comment by mahika34** [comment]
can i be assigned?

**Comment by sxijyoti** [comment]
!assign @mahika34

**Comment by mahika34** [comment]
ok working on it

**Comment by sxijyoti** [comment]
@mahika34 will look into your pr in a while and get back to you

**Comment by sxijyoti** [comment]
!deassign @mahika34

**Comment by SamridhiShreyaa** [comment]
can i be assigned please?

**Comment by sxijyoti** [comment]
!assign @SamridhiShreyaa

**Comment by SamridhiShreyaa** [comment]
going for break please give time

**Comment by sxijyoti** [comment]
!extend

**Comment by sxijyoti** [comment]
!extend 45

**Comment by SamridhiShreyaa** [comment]
!withdraw

**Comment by PerepaMoorty** [comment]
Hello There, @sjp-codes 
I am interested in this assignment.
Do you have any expectations as to what you are looking for? Or Can I use my creative imagination?

**Comment by 1anagha7** [comment]
please assign this to me

**Comment by Lalith2907** [comment]
can you pls assign this to me

**Comment by sxijyoti** [comment]
!assign @1anagha7

**Comment by sxijyoti** [comment]
!assign @Lalith2907

**Comment by 1anagha7** [comment]
@sjp-codes the program ends at a point and doesnt go further. so is it okay if I change the gui till there?

**Comment by GSuryaP** [comment]
can I get this issue?

**Comment by 1anagha7** [comment]
need 15 more mins,please

**Comment by sxijyoti** [comment]
@1anagha7 are you still working this?

**Comment by 1anagha7** [comment]
yess i am really sorry almost done

**Comment by sxijyoti** [comment]
!deassign @1anagha7

**Comment by sxijyoti** [comment]
!assign @GSuryaP

**Comment by sxijyoti** [comment]
!assign @GSuryaP

**Comment by sxijyoti** [comment]
!assign @GSuryaP

**Comment by codespiderr** [comment]
Can I be assigned to this next?

**Comment by GSuryaP** [comment]
@sjp-codes , can I get more lil time? I'm still working on this issue

**Comment by sxijyoti** [comment]
!deassign @GSuryaP

**Comment by sxijyoti** [comment]
!assign @GSuryaP

**Comment by Sami9692** [comment]
can i get assigned?

**Comment by sxijyoti** [comment]
!assign @GSuryaP

**Comment by codespiderr** [comment]
Can I get assigned to this?

**Comment by sxijyoti** [comment]
!deassign
