### ISSUE TITLE
Bulls and Cows Issue - keep track of the previous guesses

### ISSUE THREAD

**Issue by sxijyoti** [acmpesuecc/SaveMe#2]
Make a feature that would help me keep track of my previous guesses and the number of bulls and cows!
Like
```
4052 Bulls: 2 Cows:1
4053 Bulls: 2 Cows:0
```
but in the GUI not terminal!

Feel free to look up the game if you have no idea about it!

Happy hacking! :)

**Comment by NBM2062** [comment]
can i get assigned to this

**Comment by RisuKumari11** [comment]
can i get assigned this

**Comment by sxijyoti** [comment]
!assign @NBM2062

**Comment by nalin1o1** [comment]
assign me this please

**Comment by DhanushSS** [comment]
please get me assigned

**Comment by YVLNair** [comment]
imma ask you one more time big bro
plz assign this to me 🙏🙏🙏

**Comment by sxijyoti** [comment]
!deassign @NBM2062

**Comment by sxijyoti** [comment]
!assign @RisuKumari11

**Comment by sxijyoti** [comment]
!deassign @NBM2062

**Comment by sxijyoti** [comment]
!assign @RisuKumari11

**Comment by RisuKumari11** [comment]
!withdraw

**Comment by sxijyoti** [comment]
!assign @nalin1o1

**Comment by sxijyoti** [comment]
!assign @DhanushSS

**Comment by sxijyoti** [comment]
!deassign @DhanushSS

**Comment by sxijyoti** [comment]
!assign @YVLNair

**Comment by AutisticCoder-9000** [comment]
Can I get assigned this?

**Comment by sxijyoti** [comment]
!assign @AutisticCoder-9000

**Comment by sxijyoti** [comment]
!deassign @AutisticCoder-9000

**Comment by AutisticCoder-9000** [comment]
Can I get this assigned again? I believe I'm on the right track to finish it

**Comment by sxijyoti** [comment]
!assign @AutisticCoder-9000

**Comment by 1anagha7** [comment]
please assign this to me

**Comment by sxijyoti** [comment]
!assign @1anagha7

**Comment by AutisticCoder-9000** [comment]
Hello I've finished working on this issue. Can I get assigned so that I can contribute? Thanks

**Comment by sxijyoti** [comment]
!assign @AutisticCoder-9000

**Comment by 1anagha7** [comment]
really sorry,could you please extend the time? i just came back from a break to see i got assigned

**Comment by sherlockhome12** [comment]
hey can i get assigned this ??(on queue)

**Comment by sxijyoti** [comment]
!assign @1anagha7

**Comment by sxijyoti** [comment]
Please `!withdraw` yourself from your previous repositories issues

**Comment by sherlockhome12** [comment]
hey can I get this assigned??

**Comment by sxijyoti** [comment]
!deassign @AutisticCoder-9000
