### ISSUE TITLE
Give an ending to this game

### ISSUE THREAD

**Issue by sxijyoti** [acmpesuecc/SaveMe#3]
There are quests in this game so help me give an ending to this adventure game using those!
For example:
```
<2: bad ending  
2-3 : okay ending
>3: good ending
```
NOTE: 250 points are awarded to this issue but it will only be awarded depending on the difficulty level of the quest and your approach

Happy hacking! :)

**Comment by Nishanth2465** [comment]
can i solve dis issue?

**Comment by Aditya-C-S** [comment]
can you please assign #3

**Comment by sxijyoti** [comment]
!assign @Nishanth2465

**Comment by nalin1o1** [comment]
assign me this

**Comment by Nishanth2465** [comment]
@sjp-codes im going for dinner pause

**Comment by sxijyoti** [comment]
!extend 45

**Comment by sxijyoti** [comment]
@Nishanth2465 any updates

**Comment by Nishanth2465** [comment]
@sjp-codes there were some issues with the rock paper scisor section do i was trying to solve it

**Comment by Nishanth2465** [comment]
@sjp-codes im skipping that and just focusing on the ending task rn

**Comment by sxijyoti** [comment]
@Nishanth2465 put the issue up if you feel like it needs to be solved and i will give you 50 mins max for this

**Comment by sxijyoti** [comment]
!deassign @Nishanth2465

**Comment by sxijyoti** [comment]
!assign @Nishanth2465 50

**Comment by Nishanth2465** [comment]
@sjp-codes ending is done but the quests required to finish to get to the ending are broken,is that fine?

**Comment by sxijyoti** [comment]
@Nishanth2465 leave the 5th quest and move ahead for the other 4

**Comment by Darshanpawar7** [comment]
can you assign me this?

**Comment by Darshanpawar7** [comment]
@sjp-codes

**Comment by Nishanth2465** [comment]
@sjp-codes im done, im having issues submitting the fork

**Comment by sxijyoti** [comment]
!deassign @Nishanth2465

**Comment by sxijyoti** [comment]
!assign @Darshanpawar7

**Comment by Nishanth2465** [comment]
@sjp-codes submitted the pullrequest

**Comment by Omkar-Patil-08-05** [comment]
can you assign me this

**Comment by Dhan1211** [comment]
can you assign

**Comment by sxijyoti** [comment]
!assign @Omkar-Patil-08-05

**Comment by sxijyoti** [comment]
!assign @Dhan1211

**Comment by devanshishukla17** [comment]
can I get assigned to this

**Comment by sxijyoti** [comment]
!assign @devanshishukla17

**Comment by Redslayer112** [comment]
please assign me @Redslayer112 -> github username

**Comment by sxijyoti** [comment]
!assign @devanshishukla17

**Comment by Ruchavw** [comment]
can i get assigned?

**Comment by sxijyoti** [comment]
!extend 60

**Comment by sxijyoti** [comment]
!deassign @devanshishukla17

**Comment by sxijyoti** [comment]
!assign @devanshishukla17

**Comment by Aditya-C-S** [comment]
can i be assigned , i already finished the ending

**Comment by sxijyoti** [comment]
@Aditya-C-S you weren't assigned this issue

**Comment by Aditya-C-S** [comment]
no but i was assigned the fix GUI so in that itself i added the ended , but before i could send pull request i was deassigned

**Comment by sxijyoti** [comment]
@Aditya-C-S send the pull request...i will look into it but i will kudge you onmy on the ui

**Comment by Aditya-C-S** [comment]
ok will do it right away

**Comment by sxijyoti** [comment]
!deassign @devanshishukla17

**Comment by sxijyoti** [comment]
!assign @Redslayer112

**Comment by Redslayer112** [comment]
extension of time because of midnight dance?..

**Comment by Redslayer112** [comment]
im not assigned can you check please?

**Comment by sxijyoti** [comment]
!assign @Redslayer112

**Comment by sxijyoti** [comment]
@Redslayer112 deassign yourself from night manager ui enhancements #3 
`!withdraw`

**Comment by Redslayer112** [comment]
yeah done, can you assign me now? @sjp-codes

**Comment by sxijyoti** [comment]
!assign @Redslayer112

**Comment by Redslayer112** [comment]
!withdraw

**Comment by AdvaySanketi** [comment]
Hey can you assign me this issue

**Comment by pushkar-gr** [comment]
@sjp-codes  can I have this issue assigned ?

**Comment by sxijyoti** [comment]
!assign @pushkar-gr

**Comment by DushyanthReddy-gif** [comment]
can i have this issue assigned?

**Comment by pushkar-gr** [comment]
Im fixing @sjp-codes

**Comment by sxijyoti** [comment]
!deassign @pushkar-gr

**Comment by sxijyoti** [comment]
!assign @pushkar-gr

**Comment by Sami9692** [comment]
can u assign??

**Comment by sxijyoti** [comment]
!deassign @pushkar-gr
