### ISSUE TITLE
Another Quest to this game!

### ISSUE THREAD

**Issue by sxijyoti** [acmpesuecc/SaveMe#4]
Help me create another Quest for this game. You are free to choose any game of your choice but keep it between medium-difficult.
Make sure you have a skip option too.

NOTE: 350 points are awarded to this issue but it will only be awarded depending on the difficulty level of the quest and your approach

Happy hacking! :)

**Comment by nims-42** [comment]
can i get assigned to this pls?

**Comment by sxijyoti** [comment]
!assign @crimsonims

**Comment by nalin1o1** [comment]
assign me this

**Comment by nims-42** [comment]
@sjp-codes  im going for dinner rn, could you please extend my time?  thank you

**Comment by sxijyoti** [comment]
!extend 45

**Comment by sxijyoti** [comment]
@crimsonims any updates

**Comment by nims-42** [comment]
sorry need more time

**Comment by sxijyoti** [comment]
!extend 45

**Comment by sxijyoti** [comment]
!assign @crimsonims

**Comment by sxijyoti** [comment]
!deassign @crimsonims

**Comment by sxijyoti** [comment]
!assign @crimsonims 50

**Comment by DHANUVARSHA04** [comment]
Can you please assign me this?

**Comment by Darshanpawar7** [comment]
please assign me this ?

**Comment by nims-42** [comment]
hey im still working on it, question is done, debugging some errors

**Comment by sxijyoti** [comment]
@crimsonims meet me

**Comment by DHANUVARSHA04** [comment]
Can you assign me this please

**Comment by DHANUVARSHA04** [comment]
Can you assign me this please

**Comment by sxijyoti** [comment]
!deassign @crimsonims

**Comment by sxijyoti** [comment]
!assign @crimsonims 65

**Comment by sxijyoti** [comment]
!deassign @crimsonims

**Comment by AkshayaR11** [comment]
can i get assigned for this

**Comment by sxijyoti** [comment]
!assign @AkshayaR11 60

**Comment by nims-42** [comment]
sent a pr

**Comment by sxijyoti** [comment]
!assign @DHANUVARSHA04

**Comment by sxijyoti** [comment]
!deassign @DHANUVARSHA04

**Comment by PerepaMoorty** [comment]
Do you have anything specific in mind, As to the flow or the pacing of the "Quest"?

**Comment by devanshishukla17** [comment]
hi can you please assign me this

**Comment by sxijyoti** [comment]
!assign @devanshishukla17

**Comment by AutisticCoder-9000** [comment]
Can I get assigned to this?

**Comment by Aditya-C-S** [comment]
@sjp-codes can u please assign me this

**Comment by devanshishukla17** [comment]
can I get some more time I am almost there

**Comment by sxijyoti** [comment]
!deassign @devanshishukla17

**Comment by sxijyoti** [comment]
!assign @devanshishukla17

**Comment by AutisticCoder-9000** [comment]
Can I please get assigned this?

**Comment by sxijyoti** [comment]
!deassign @devanshishukla17

**Comment by DushyanthReddy-gif** [comment]
can you assign me this?
