### ISSUE TITLE
.

### ISSUE THREAD

**Issue by sxijyoti** [acmpesuecc/SaveMe#6]
Please don't edit the contributing and requirement guidelines

**Comment by yuritaba** [comment]
Whats up?! Can I contribute to your code?

**Comment by yuritaba** [comment]
I would love to close some of the issues if you'd like

**Comment by sjp-codes** [comment]
@yuritaba hey im sorry its not up for contribution yet

**Comment by yuritaba** [comment]
@sjp-codes do you have any prediction about when the contributions can get accepted? I'm working in a college course that requires a certain number of open source contributions to small projects. I would really like to contribute to yours. One small pull request would already help me a lot! Thank you in advance.

**Comment by sjp-codes** [comment]
@yuritaba feel free to work on them from sunday if they remain unsolved(maybe on my original repository itself.) This is actually for a hackathon for my college to ye:")
Just leave an issue on my org repo
