### ISSUE TITLE
Make the pop-up windows look better

### ISSUE THREAD

**Issue by sxijyoti** [acmpesuecc/SaveMe#7]
Adjust the pop-up and give it a theme to align with the game better

Happy hacking! :)

**Comment by asmitdesai** [comment]
can you assign it to me

**Comment by sxijyoti** [comment]
!assign @asmitdesai

**Comment by ashyune** [comment]
can I be assigned please

**Comment by Andy34G7** [comment]
Can I assigned to this issue?

**Comment by mahika34** [comment]
can i be assigned

**Comment by sxijyoti** [comment]
!assign @ashyune 60

**Comment by sxijyoti** [comment]
!assign @mahika34  60

**Comment by sxijyoti** [comment]
!deassign

**Comment by sxijyoti** [comment]
!assign @ashyune

**Comment by sxijyoti** [comment]
!deassign @asmitdesai

**Comment by sxijyoti** [comment]
!assign @mahika34

**Comment by Bhumi-Sinha** [comment]
assign me

**Comment by sxijyoti** [comment]
!assign @Bhumi-Sinha

**Comment by sxijyoti** [comment]
!assign @Bhumi-Sinha

**Comment by DhanushSS** [comment]
pls assign me

**Comment by sxijyoti** [comment]
!deassign @Bhumi-Sinha

**Comment by sxijyoti** [comment]
!assign @DhanushSS

**Comment by YVLNair** [comment]
can you assign the issue to me next

**Comment by sxijyoti** [comment]
!assign @YVLNair

**Comment by sxijyoti** [comment]
!deassign @YVLNair

**Comment by suchiradi** [comment]
can you assign the issue to me

**Comment by sxijyoti** [comment]
!assign @suchiradi

**Comment by suchiradi** [comment]
deassign me

**Comment by sxijyoti** [comment]
!deassign @suchiradi

**Comment by DhruvHegde** [comment]
can you assign me this

**Comment by Gunika-Goel** [comment]
can i be assigned this ?

**Comment by sxijyoti** [comment]
!assign @Gunika-Goel

**Comment by Gunika-Goel** [comment]
@sjp-codes it is showing no one assigned

**Comment by sxijyoti** [comment]
@Gunika-Goel unable to assign it to you currently but you can work on it now
Will get back to it in a while

**Comment by Gunika-Goel** [comment]
Ok starting working on it then

**Comment by devanshishukla17** [comment]
can you please assign me this

**Comment by AutisticCoder-9000** [comment]
Can you assign this to me?

**Comment by sxijyoti** [comment]
!deassign

**Comment by sxijyoti** [comment]
!assign @devanshishukla17

**Comment by Sami9692** [comment]
can u assign this??????//

**Comment by devanshishukla17** [comment]
can I please continue working on this I'm almost there

**Comment by devanshishukla17** [comment]
!withdraw

**Comment by Anyaaa-2** [comment]
can i please get assigned
