### ISSUE TITLE
Update the Game Description in the README.md

### ISSUE THREAD

**Issue by sxijyoti** [acmpesuecc/SaveMe#8]
Please don't change the guidelines for requirements and contribution
Happy hacking! :)

**Comment by 1anagha7** [comment]
can i get assigned please?

**Comment by sxijyoti** [comment]
!assign @1anagha7

**Comment by ashyune** [comment]
can I be assigned

**Comment by Andy34G7** [comment]
Can I get assigned to this issue?

**Comment by Tarun600GK** [comment]
can i get assigned

**Comment by SavvyHex** [comment]
Can I get assigned?

**Comment by ashyune** [comment]
I had to go for dinner, can my timer be increased please? I came back around 9:10

**Comment by sxijyoti** [comment]
!assign @ashyune

**Comment by YVLNair** [comment]
ayy big bro plz assign ts to me!!!

**Comment by sxijyoti** [comment]
!deassign

**Comment by sxijyoti** [comment]
!assign @ashyune

**Comment by sxijyoti** [comment]
!deassign @1anagha7

**Comment by sxijyoti** [comment]
!assign @ashyune

**Comment by sxijyoti** [comment]
!assign @Andy34G7

**Comment by Bhumi-Sinha** [comment]
assign plz

**Comment by DHANUVARSHA04** [comment]
assign please

**Comment by DushyanthReddy-gif** [comment]
can I get assigned this?

**Comment by DushyanthReddy-gif** [comment]
can i please get this assigned?

**Comment by sxijyoti** [comment]
!deassign @Andy34G7

**Comment by sxijyoti** [comment]
!assign @Tarun600GK

**Comment by sxijyoti** [comment]
!assign @SavvyHex

**Comment by DushyanthReddy-gif** [comment]
can i get this assigned to me?

**Comment by SavvyHex** [comment]
I submitted a PR, please check it out

**Comment by atharv24mittal** [comment]
can i get it assigned pls

**Comment by sxijyoti** [comment]
!deassign @SavvyHex
